#!/bin/bash
# Description: Freshen up the project's dependencies and data
# Meta: order=2

docker_compose_up_if_necessary

run: composer install
run: npm install --no-progress --quiet

# run: artisan mysql-snapshots:load
# run: npm run dev

